### ISSUE TITLE
Consider delaying assignment to the atomic variable until the end

### ISSUE THREAD

**Issue by jonesmz** [sawickiap/str_view#2]
https://github.com/sawickiap/str_view/blob/581da67d0bb936359702c5b93a76a516eb5971b6/str_view.hpp#L324

Atomic operations the most expensive thing possible, but here you can just use temporaries and initialize at the end of the function.

**Comment by sawickiap** [comment]
Thank you for the suggestion. Atomics are no longer used by the library since version 2.0.0.
