### ISSUE TITLE
nullChar can be constexpr

### ISSUE THREAD

**Issue by jonesmz** [sawickiap/str_view#4]
https://github.com/sawickiap/str_view/blob/581da67d0bb936359702c5b93a76a516eb5971b6/str_view.hpp#L459

**Comment by sawickiap** [comment]
It cannot be `constexpr` because I use the address of this variable. Adding `constexpr` results in the following compiler error:
```
str_view.hpp(546): warning C4172: returning address of local variable or temporary: nullChar
```
