### ISSUE TITLE
You have no guarantee that the length of an unknown length string won't change out from under you

### ISSUE THREAD

**Issue by jonesmz** [sawickiap/str_view#5]
https://github.com/sawickiap/str_view/blob/581da67d0bb936359702c5b93a76a516eb5971b6/str_view.hpp#L463

The string that you're pointing to may not have the location of the buffer change out from under it, but you have no guarantees that the contents of the buffer aren't changing.

So your assumption here that the length remains the same may not be safe.

**Comment by jonesmz** [comment]
Instead of allocating a buffer that you hold onto indefinitely, an alternative that has different tradeoffs would be to allocate an object that behaves like a std::unique_ptr, but has an implicit conversion to const char*.

That would allow you to allocate a "snapshot" of the data at the moment that c_str() gets called, which would be cleaned up automatically.

Of course, that has some pitfalls as well. If someone stores the result of c_str(), like:

    const char * c = str.c_str();

It'll automatically implicitly convert, and the buffer will get destructed immediately. Bit one of my co-workers, got very-difficult to reproduce memory corruption.

So it's not exactly fool-proof, and I'm certainly not saying you *should* do that.

Just food for thought.

Maybe you can think of a nice way to make it work :-)

**Comment by sawickiap** [comment]
Thank you for the suggestions and sorry for delayed response.

Documentation says:
> The original string must remain alive and unchanged as long as the view object is alive and points to it. Otherwise behavior is undefined.

This is all I can do to guarantee the original string doesn't change or disappear from memory when `str_view` for it is used.

Your second suggestion sounds quite dangerous. I would rather leave the behavior as-is, similar to `std::string::c_str()` is doing.
