### ISSUE TITLE
You have a pretty serious multi-threaded data safety issue

### ISSUE THREAD

**Issue by jonesmz** [sawickiap/str_view#6]
https://github.com/sawickiap/str_view/blob/581da67d0bb936359702c5b93a76a516eb5971b6/str_view.hpp#L530

Imagine 2 threads.

On thread A, we perform a comparison between two str_view_template objects.

The compare function acquires the values of both str_view_template objects lengths.

The second thread, thread B, assigns a new value to one of the str_view_templates. Due to the vagaries of the processor and OS scheduler the entire assignment operation completes on thread B before thread A loads the value of the data pointer.

So now you're comparing with the old length, but the new value.

You can resolve an aspect of this problem by storing the length and pointer as a single atomic-ally changable value.

One 32bit platforms you'll have sizeof(size_t) + sizeof(void*), so 64bit. As far as I know, most 32 bit platforms have support for *some* atomic 64 bit operations.

On 64bit platforms you have 128 bits, not sure about atomic operation support for 128 bit operations.

But, sadly, this does *not* save you from the classic ABA problem, so I'm not sure that's really a solution. Then again, maybe the ABA problem isn't relevant here.

I think a better way to handle these issues would be to explicitly consider this entire class to be non-thread safe.

You can't guarantee that the data you're pointing at is safe to access from across thread boundaries unless you copy the data. Anything passed into you can disappear as soon as the place where the assignment operator is called goes out of scope. You might get lucky and the variable in question is a member variable to some object in the heap, but it's just as likely that the variable exists only on the stack.

**Comment by sawickiap** [comment]
Thank you for the extensive description of the problem and sorry for my delayed response. You are right. The `str_view` class is defined as not thread-safe since version 2.0.0.
